<?php

/**
 * @file
 * Contains gamification_points.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function gamification_points_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the gamification_points module.
    case 'help.page.gamification_points':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Gamification points') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function gamification_points_theme() {
  return [
    'gamification_points' => [
      'render element' => 'children',
    ],
  ];
}
